# Generated by Django 3.0.9 on 2020-08-03 13:12

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supermarkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrijf', models.TextField()),
                ('adres', models.TextField()),
                ('plaatsnaam', models.TextField()),
                ('uitverkochte_producten', django_mysql.models.ListTextField(models.CharField(max_length=100), size=None)),
            ],
        ),
    ]
