# Generated by Django 3.0.9 on 2020-09-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uitverkochte_producten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.TextField()),
                ('supermarkt_id', models.IntegerField()),
                ('datum', models.DateTimeField()),
            ],
        ),
    ]
