# Generated by Django 3.0.9 on 2020-09-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkten', '0003_remove_supermarkt_uitverkochte_producten'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uitverkochte_producten',
            new_name='Uitverkochte_product',
        ),
    ]
