# Generated by Django 3.0.9 on 2020-09-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkten', '0004_auto_20200903_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supermarkt',
            name='id',
        ),
        migrations.AddField(
            model_name='supermarkt',
            name='supermarkt_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
